import AppKit
import Combine
import FilmStudioCore
import Foundation

@MainActor
final class PalmierFilmStudioModel: ObservableObject {
    struct RuntimeDependency: Identifiable, Equatable {
        let id: String
        let label: String
        let available: Bool
        let detail: String
    }

    enum StudioError: LocalizedError {
        case noProject
        case noPlayableCut
        case noInstalledAgentModel
        case noPalmierProject
        case importRejected

        var errorDescription: String? {
            switch self {
            case .noProject: "Open or create a film first."
            case .noPlayableCut: "GRACE has not produced a playable cut yet."
            case .noInstalledAgentModel: "mere.run did not report an installed local agent model that it can start."
            case .noPalmierProject: "Open a Palmier project before importing the GRACE cut."
            case .importRejected: "Palmier did not import the GRACE cut. Check that the generated file is a supported media type."
            }
        }
    }

    @Published private(set) var snapshot: FilmWorkspaceSnapshot?
    @Published private(set) var runtimeDependencies: [RuntimeDependency] = []
    @Published private(set) var selectedAgentModel: MereRunAgentModel?
    @Published private(set) var isBusy = false
    @Published private(set) var activity = ""
    @Published var errorMessage: String?
    @Published var noticeMessage: String?

    @Published var filmToolExecutable: String {
        didSet { UserDefaults.standard.set(filmToolExecutable, forKey: "palmierFilmStudio.filmToolExecutable") }
    }
    @Published var piExecutable: String {
        didSet { UserDefaults.standard.set(piExecutable, forKey: "palmierFilmStudio.piExecutable") }
    }
    @Published var mereRunExecutable: String {
        didSet { UserDefaults.standard.set(mereRunExecutable, forKey: "palmierFilmStudio.mereRunExecutable") }
    }

    @Published var newFilmIdea = ""
    @Published var newFilmTitle = ""
    @Published var newFilmDuration = 45
    @Published var newFilmDirectory = FileManager.default.homeDirectoryForCurrentUser
        .appending(path: "Movies/Palmier Films", directoryHint: .isDirectory)

    let durationOptions = [15, 30, 45, 60, 90, 120]
    private var commandTask: Task<Void, Never>?

    init() {
        filmToolExecutable = UserDefaults.standard.string(forKey: "palmierFilmStudio.filmToolExecutable") ?? "mere-film-tools"
        piExecutable = UserDefaults.standard.string(forKey: "palmierFilmStudio.piExecutable") ?? "pi"
        mereRunExecutable = UserDefaults.standard.string(forKey: "palmierFilmStudio.mereRunExecutable")
            ?? ProcessInfo.processInfo.environment["MERE_RUN_EXECUTABLE"]
            ?? "mere.run"

        if let lastRun = UserDefaults.standard.string(forKey: "palmierFilmStudio.lastRunManifest") {
            openProject(URL(fileURLWithPath: lastRun), reportErrors: false)
        }
    }

    var pendingGate: String? {
        guard let approvals = snapshot?.project.approvals else { return nil }
        return ["brief", "treatment", "production", "picture-lock", "delivery"]
            .first { approvals[$0]?.status == "pending" }
    }

    var runtimeReady: Bool {
        let required = Set(["mere-film-tools", "mere.run", "pi", "ffmpeg", "ffprobe", "agent-model"])
        let available = Set(runtimeDependencies.filter(\.available).map(\.id))
        return required.isSubset(of: available)
    }

    var effectiveNewFilmTitle: String {
        let title = newFilmTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        if !title.isEmpty { return title }
        let inferred = newFilmIdea.split(whereSeparator: \.isWhitespace).prefix(6).joined(separator: " ")
        return inferred.isEmpty ? "Untitled Film" : inferred
    }

    var newFilmProjectDirectory: URL {
        let slug = effectiveNewFilmTitle.lowercased()
            .replacingOccurrences(of: "[^a-z0-9]+", with: "-", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: "-"))
        return newFilmDirectory.appending(path: slug.isEmpty ? "untitled-film" : slug, directoryHint: .isDirectory)
    }

    func chooseProject() {
        let panel = NSOpenPanel()
        panel.title = "Open GRACE Film"
        panel.message = "Choose the run.json generated by mere-film-tools."
        panel.prompt = "Open Film"
        panel.allowedContentTypes = [.json]
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        guard panel.runModal() == .OK, let url = panel.url else { return }
        openProject(url)
    }

    func chooseNewFilmDirectory() {
        let panel = NSOpenPanel()
        panel.title = "Choose Film Location"
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.canCreateDirectories = true
        panel.directoryURL = newFilmDirectory
        guard panel.runModal() == .OK, let url = panel.url else { return }
        newFilmDirectory = url
    }

    func openProject(_ input: URL, reportErrors: Bool = true) {
        do {
            let runManifest = input.lastPathComponent == "run.json" ? input : input.appending(path: "run.json")
            let loaded = try FilmProjectLoader.load(runManifest: runManifest)
            snapshot = loaded
            UserDefaults.standard.set(loaded.runManifest.path, forKey: "palmierFilmStudio.lastRunManifest")
            errorMessage = nil
        } catch {
            if reportErrors { errorMessage = error.localizedDescription }
        }
    }

    func refreshProject() {
        guard let runManifest = snapshot?.runManifest else { return }
        openProject(runManifest)
    }

    func closeProject() {
        commandTask?.cancel()
        isBusy = false
        activity = ""
        snapshot = nil
        noticeMessage = nil
        UserDefaults.standard.removeObject(forKey: "palmierFilmStudio.lastRunManifest")
    }

    func refreshRuntime() async {
        var dependencies: [RuntimeDependency] = []
        let filmTool = resolvedDependency(id: "mere-film-tools", label: "mere-film-tools", value: filmToolExecutable)
        dependencies.append(filmTool.row)
        let mereRun = resolvedDependency(id: "mere.run", label: "mere.run", value: mereRunExecutable)
        dependencies.append(mereRun.row)

        do {
            let pi = try PiExecutableResolver.resolve(piExecutable)
            dependencies.append(.init(id: "pi", label: "Pi", available: true, detail: pi.path))
        } catch {
            dependencies.append(.init(id: "pi", label: "Pi", available: false, detail: error.localizedDescription))
        }

        dependencies.append(resolvedDependency(id: "ffmpeg", label: "ffmpeg", value: "ffmpeg").row)
        dependencies.append(resolvedDependency(id: "ffprobe", label: "ffprobe", value: "ffprobe").row)

        selectedAgentModel = nil
        if let mereRunURL = mereRun.url {
            do {
                let status = try await MereRunAgentClient(executable: mereRunURL.path).status()
                if let model = status.bestInstalledModel {
                    selectedAgentModel = model
                    dependencies.append(.init(id: "agent-model", label: "Local agent model", available: true, detail: "\(model.displayName) · \(model.id)"))
                } else {
                    dependencies.append(.init(id: "agent-model", label: "Local agent model", available: false, detail: StudioError.noInstalledAgentModel.localizedDescription))
                }
            } catch {
                dependencies.append(.init(id: "agent-model", label: "Local agent model", available: false, detail: error.localizedDescription))
            }
        } else {
            dependencies.append(.init(id: "agent-model", label: "Local agent model", available: false, detail: "mere.run is unavailable."))
        }

        runtimeDependencies = dependencies
    }

    func createFilm() {
        let idea = newFilmIdea.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !idea.isEmpty else {
            errorMessage = "Enter an idea for the film."
            return
        }
        let title = effectiveNewFilmTitle
        let output = newFilmProjectDirectory
        let duration = newFilmDuration
        let filmToolExecutable = filmToolExecutable
        let piExecutable = piExecutable

        perform("Creating film…") { [weak self] in
            try FileManager.default.createDirectory(at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
            let pi = try PiExecutableResolver.resolve(piExecutable)
            let runManifest = try await FilmToolClient(executable: filmToolExecutable).plan(
                idea: idea,
                title: title,
                durationSeconds: duration,
                outputDirectory: output,
                piCommand: pi.path
            )
            self?.openProject(runManifest)
            self?.newFilmIdea = ""
            self?.newFilmTitle = ""
        }
    }

    func approvePendingGate() {
        guard let runManifest = snapshot?.runManifest, let gate = pendingGate else { return }
        let filmToolExecutable = filmToolExecutable
        perform("Approving \(gate)…") { [weak self] in
            try await FilmToolClient(executable: filmToolExecutable).approve(
                runManifest: runManifest,
                gate: gate,
                note: "Approved in Palmier Pro after reviewing the current GRACE evidence.",
                approvedBy: NSFullUserName().isEmpty ? "macOS user" : NSFullUserName()
            )
            self?.noticeMessage = "Approved \(gate)."
        }
    }

    func advance() {
        guard let runManifest = snapshot?.runManifest else {
            errorMessage = StudioError.noProject.localizedDescription
            return
        }
        let filmToolExecutable = filmToolExecutable
        let piExecutable = piExecutable
        let mereRunExecutable = mereRunExecutable
        perform("Advancing production…") { [weak self] in
            let context = try await Self.resolveAgentContext(piExecutable: piExecutable, mereRunExecutable: mereRunExecutable)
            _ = try await FilmToolClient(executable: filmToolExecutable).advance(
                runManifest: runManifest,
                piCommand: context.pi.path,
                piProvider: "mere-run",
                piModel: context.model.id
            )
            self?.selectedAgentModel = context.model
        }
    }

    func runReview() {
        guard let runManifest = snapshot?.runManifest else {
            errorMessage = StudioError.noProject.localizedDescription
            return
        }
        let filmToolExecutable = filmToolExecutable
        let piExecutable = piExecutable
        let mereRunExecutable = mereRunExecutable
        perform("Running review…") { [weak self] in
            let context = try await Self.resolveAgentContext(piExecutable: piExecutable, mereRunExecutable: mereRunExecutable)
            _ = try await FilmToolClient(executable: filmToolExecutable).review(
                runManifest: runManifest,
                piCommand: context.pi.path,
                piProvider: "mere-run",
                piModel: context.model.id
            )
            self?.selectedAgentModel = context.model
        }
    }

    func recover() {
        guard let runManifest = snapshot?.runManifest else {
            errorMessage = StudioError.noProject.localizedDescription
            return
        }
        let filmToolExecutable = filmToolExecutable
        perform("Recovering interrupted work…") {
            _ = try await FilmToolClient(executable: filmToolExecutable).recover(runManifest: runManifest)
        }
    }

    func importPlayableCut(into editor: EditorViewModel) {
        guard let cutURL = snapshot?.playableCutURL else {
            errorMessage = StudioError.noPlayableCut.localizedDescription
            return
        }
        perform("Importing cut into Palmier…", refreshAfterward: false) { [weak self, weak editor] in
            guard let editor else { throw StudioError.noPalmierProject }
            let summary = try await editor.importFinderItems([cutURL], into: editor.mediaPanelCurrentFolderId, finalize: true)
            guard summary.assetCount > 0 else { throw StudioError.importRejected }
            self?.noticeMessage = "Imported \(cutURL.lastPathComponent) into Palmier."
        }
    }

    func revealPlayableCut() {
        guard let cutURL = snapshot?.playableCutURL else {
            errorMessage = StudioError.noPlayableCut.localizedDescription
            return
        }
        NSWorkspace.shared.activateFileViewerSelecting([cutURL])
    }

    func dismissMessages() {
        errorMessage = nil
        noticeMessage = nil
    }

    private func perform(
        _ description: String,
        refreshAfterward: Bool = true,
        operation: @escaping @MainActor () async throws -> Void
    ) {
        guard !isBusy else { return }
        isBusy = true
        activity = description
        errorMessage = nil
        noticeMessage = nil
        commandTask?.cancel()
        commandTask = Task { @MainActor [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.activity = ""
            }
            do {
                try await operation()
                if refreshAfterward { self.refreshProject() }
            } catch is CancellationError {
                return
            } catch {
                self.errorMessage = error.localizedDescription
            }
        }
    }

    private func resolvedDependency(id: String, label: String, value: String) -> (row: RuntimeDependency, url: URL?) {
        do {
            let url = try FilmToolClient.resolveExecutable(value)
            return (.init(id: id, label: label, available: true, detail: url.path), url)
        } catch {
            return (.init(id: id, label: label, available: false, detail: error.localizedDescription), nil)
        }
    }

    private static func resolveAgentContext(
        piExecutable: String,
        mereRunExecutable: String
    ) async throws -> (pi: URL, model: MereRunAgentModel) {
        let pi = try PiExecutableResolver.resolve(piExecutable)
        let mereRun = try FilmToolClient.resolveExecutable(mereRunExecutable)
        let status = try await MereRunAgentClient(executable: mereRun.path).status()
        guard let model = status.bestInstalledModel else { throw StudioError.noInstalledAgentModel }
        return (pi, model)
    }
}
